obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_PM_CABLE_DETECTION) += lge_cable_detection.o
obj-$(CONFIG_LGE_PM_CHARGING_CONTROLLER) += lge_charging_controller.o
ifdef CONFIG_LGE_PM_CHARGING_SCENARIO_V18
obj-$(CONFIG_LGE_PM_CHARGING_SCENARIO) += lge_charging_scenario_v18.o
else
obj-$(CONFIG_LGE_PM_CHARGING_SCENARIO) += lge_charging_scenario.o
endif
obj-$(CONFIG_LGE_PM_UNIFIED_NODE) += lge_power_sysfs.o
obj-$(CONFIG_LGE_ACC_NT) += lge_acc_nt.o
obj-$(CONFIG_LGE_PM_SUPPORT_LG_POWER_CLASS) += power/
